[versions]
androidxJunit = "1.2.1"
appcompat = "1.7.0"
coreKtx = "1.13.0"  # Updated from 1.12.0
activityCompose = "1.8.2"
agp = "8.9.0"
composeBom = "2023.10.01"
converterGson = "2.9.0"
coreKtxVersion = "1.15.0"
datastorePreferences = "1.1.3"
espressoCore = "3.5.1"  # Downgraded from 3.6.1
firebaseAuthKtx = "23.2.0"
firebaseDatabaseKtx = "21.0.0"
firebaseFirestoreKtx = "25.1.2"
firebaseMessagingKtx = "24.1.0"
firebaseStorageKtx = "21.0.1"
glide = "5.0.0-rc01"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "1.9.22"
kotlinxCoroutinesAndroid = "1.7.3"
kotlinxCoroutinesPlayServices = "1.7.3"
lifecycleRuntimeCompose = "2.7.0"
lifecycleRuntimeKtx = "2.7.0"
lifecycleViewmodelCompose = "2.7.0"
mapsCompose = "4.3.3"
material = "1.11.0"  # Downgraded from 1.12.0
navigationCompose = "2.7.7"
places = "3.4.0"  # Downgraded from 4.1.0
playServicesMaps = "18.2.0"
retrofit = "2.9.0"
ucrop = "2.2.8"
constraintlayout = "2.1.4"
coilCompose = "2.6.0"
google-services = "4.4.2"
uiAndroid = "1.7.8"  # Added plugin version

[libraries]
# AndroidX
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1150 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Testing
androidx-junit-v121 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Firebase
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }

# Other
material = { module = "com.google.android.material:material", version.ref = "material" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }